name: "Check mypy"
on:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: jpetrucciani/mypy-check@master
        with:
          path: "custom_components"